### ISSUE TITLE
Make fields editable from within the UI

### ISSUE THREAD

**Issue by lmperry** [scitran/sdm#19]
Some of the fields that should be editable: 

1. Project/Collection Name
2. Subject Code
3. Acquisition Description
4. Data Type (this may have to be a drop-down list so that we don't get a bunch of non-sense data types)

**Comment by gsfr** [comment]
Subject code, rather than subject name.

**Comment by rentzso** [comment]
@lmperry should we allow the creation of new datatypes?
Or we should use a "predefined" datatype's list?
Currently a dropdown is defined in the search view but only datatypes existing in the data are listed there.

**Comment by lmperry** [comment]
@rentzso I believe a predefined list is the way to go for now. Eventually it would be nice to allow the user to create a new type, but that could get messy, and I believe the API has some logic based on datatype and we shouldn't break that. 

This is what is currently at the CNI when someone tries to search:
![screen shot 2015-04-23 at 2 51 17 pm](https://cloud.githubusercontent.com/assets/2119651/7308317/3ab08e70-e9c8-11e4-8ac7-b42d873a2650.png)

**Comment by mrjeffs** [comment]
If I may make a comment from the sidelines:
If the data types are to remain fixed to avoid breakages, then I would like to make a feature request to include meg fif files as a data type and format.

Jeff


Sent from Outlook<http://taps.io/outlookmobile>




On Thu, Apr 23, 2015 at 2:05 PM -0700, "Renzo Frigato" <notifications@github.com<mailto:notifications@github.com>> wrote:


@lmperry<https://github.com/lmperry> should we allow the creation of new datatypes?
Or we should use a "predefined" datatype's list?
Currently a dropdown is defined in the search view but only datatypes existing in the data are listed there.

-

**Comment by gsfr** [comment]
I think MEG will actually be its own data domain. That said, we are currently in the process of coming up with a better model for representing domains and types and all that. Stay tuned.
