### ISSUE TITLE
Remove hover-over toolbar from the table

### ISSUE THREAD

**Issue by lmperry** [scitran/sdm#21]
Remove the hover-over toolbar from the table and add the behavior that clicking on an item in the table will bring up the modal.

**Comment by rentzso** [comment]
Feature is ready on branch removeToolbar. Before merging with master, I believe we need first to enable the remove button in the collection's view.

**Comment by lmperry** [comment]
That's right. Furthermore, we should gray-out the non-functional Trash icon in the main table and alert the user that they cannot delete items if they check something and click it. A message like "Your selection cannot be deleted" would suffice.
