### ISSUE TITLE
Row count in column headers is missing

### ISSUE THREAD

**Issue by lmperry** [scitran/sdm#29]
What we got prior to fb4d6bb:
![screen shot 2015-05-15 at 3 35 37 pm](https://cloud.githubusercontent.com/assets/2119651/7662973/2ceefef0-fb18-11e4-8d1c-dfd44a47a245.png)

What we see at fb4d6bb:
![screen shot 2015-05-15 at 3 35 51 pm](https://cloud.githubusercontent.com/assets/2119651/7662971/24b811c2-fb18-11e4-8edd-895663b1f00c.png)

**Comment by rentzso** [comment]
fixed in commit a0c4b231d721ca2a069737f951e9cfa090055d3a
