### ISSUE TITLE
Remove/Delete empty project

### ISSUE THREAD

**Issue by lmperry** [scitran/sdm#35]
Administrators should be able to delete empty projects.

**Comment by lmperry** [comment]
Perhaps the 'no data' icon could become a 'delete' button, giving the user the option of deleting the empty project. More thought on this would be helpful.

**Comment by gsfr** [comment]
I like that idea.
When an admin clicks the 'no data' icon, it turns into a delete button, and clicking that deletes the project.
The DELETE method is already implemented in the API.
