### ISSUE TITLE
Add a DICOM viewer

### ISSUE THREAD

**Issue by lmperry** [scitran/sdm#36]
It would be good to start considering the addition of a DICOM viewer to the system to accommodate acquisitions that cannot be converted to NIfTI. There are a few open-source JS DICOM viewers (e.g. [Dicom Web Viewer](http://ivmartel.github.io/dwv/)  looks promising). 

This may not be possible with the current storage of DICOMs in 'tar.gz' format - it may have to wait until we get 'zip' storage implemented. At that point we can consider using a simple JS lib for dealing with 'zip', like [zip.js](https://gildas-lormeau.github.io/zip.js/)

**Comment by rmchamberlain** [comment]
Papaya can read DICOM - is there a certain feature that it's missing you think we should have?

**Comment by lmperry** [comment]
No, I think Papaya would be ideal.

**Comment by gsfr** [comment]
Papaya is easy because we already have it, but it sucks because it does not respect the NIfTI transform matrix.
@aaltepet Have you guys looked further into chafey/cornerstone? Looks like it only does DICOM out of the box, but not NIfTI.

**Comment by aaltepet** [comment]
@gsfr - I've done some integration of cornerstone into Imbio's launchpad website; it was quite easy.  Cornerstone is a great viewer, and has builtin support for dicom.  I'm not aware of nifti support, but I think building it would be easy.  Cornerstone is build with pluggable image loaders in mind.  You'll need to write an nifti image loader; nifti is an easy file format (and maybe there are js nifti parsers available already).

See:
https://github.com/chafey/cornerstoneWebImageLoader
for a simple image loader example
And:
https://github.com/chafey/cornerstoneWADOImageLoader
for the more complex dicom WADO image loader

From what I've seen about cornerstone already, it has great features out of the box, and is built with extensibility in mind.

**Comment by mrjeffs** [comment]
My 2c: eric has been working on pyvis. Wonder if that is a candidate? J


From: Andy
Reply-To: scitran/sdm
Date: Thursday, July 2, 2015 at 8:10 AM
To: scitran/sdm
Subject: Re: [sdm] Add a DICOM viewer (#36)


@gsfr<https://github.com/gsfr> - I've done some integration of cornerstone into Imbio's launchpad website; it was quite easy. Cornerstone is a great viewer, and has builtin support for dicom. I'm not aware of nifti support, but I think building it would be easy. Cornerstone is build with pluggable image loaders in mind. You'll need to write an nifti image loader; nifti is an easy file format (and maybe there are js nifti parsers available already).

See:
https://github.com/chafey/cornerstoneWebImageLoader
for a simple image loader example
And:
https://github.com/chafey/cornerstoneWADOImageLoader
for the more complex dicom WADO image loader

From what I've seen about cornerstone already, it has great features out of the box, and is built with extensibility in mind.

**Comment by mrjeffs** [comment]
Actually there is a kind of old PR into nibabel to add a generic MRI viewer
using matplotlib. That might be the path of least resistance. I can try to
resurrect it if there is interest.
