### ISSUE TITLE
Subject code returns undefined in Search

### ISSUE THREAD

**Issue by lmperry** [scitran/sdm#37]
The subject field is shown as '(undefined)' when viewing search results.

![screen shot 2015-07-06 at 9 57 57 am](https://cloud.githubusercontent.com/assets/2119651/8528078/871074a6-23c5-11e5-9108-e05e77676d0e.png)

**Comment by gsfr** [comment]
Subject code was an API-side fix only. Search by exam number was failing because search was done by integer, but DB contains strings (correctly so).
