### ISSUE TITLE
Render script files (.m, .py, .sh...) as text files in modal

### ISSUE THREAD

**Issue by lmperry** [scitran/sdm#41]
Currently these have no associated viewer.

**Comment by lmperry** [comment]
also '.bvec' and '.bval' files should be rendered as text.

**Comment by rentzso** [comment]
@gsfr : are we setting the mime type of the attachment anywhere in the api? the viewer depends on that to render each file.

We tried to change the nginx config file but with no luck.

**Comment by gsfr** [comment]
nginx is not the right place. Custom mime types are currently configured in [util.py](https://github.com/scitran/api/blob/master/util.py#L24). Probably not a good longterm choice, but here we are.
The ```filetype``` field of each file should be used to offer the correct viewer, as you already to for nifti and montage. And when you download a file with ```?view=true``` the mime type is set correctly set in the ```Content-Type``` http header.

**Comment by rentzso** [comment]
closed with commit: https://github.com/scitran/api/commit/17483131ecee3669da063e337614de07f379893c

As a side note, attachments already uploaded will not show as text/plain

**Comment by lmperry** [comment]
@rentzso I can confirm that bvec, bvals, sh, py all work. However, .m files are downloaded when clicking on the view icon.
