### ISSUE TITLE
add tooltip to "Actions" menu

### ISSUE THREAD

**Issue by rentzso** [scitran/sdm#45]
A message is needed to clarify why and when this menu is inactive.

**Comment by lmperry** [comment]
I would argue that the menu should always be active (drop down), but the items that require data to be selected are grayed out, when you hover over a grayed out item it will tell you to select data...

**Comment by rentzso** [comment]
@lmperry done. Not sure if the tooltip is still needed now...

**Comment by lmperry** [comment]
Thats great! I don't think a tool tip is necessary.
