### ISSUE TITLE
Allow project creation in the admin modal

### ISSUE THREAD

**Issue by rentzso** [scitran/sdm#46]
at the moment it is only possible to create projects from the moving sessions toolbar.

A more straightforward interface is needed.

**Comment by lmperry** [comment]
What about adding a 'Create project' item in the 'actions' dropdown? It's not really an administrative task as it has nothing to do with users. Furthermore, perhaps we should have the actions menu always expand, but the items that are not possible without data selected, or admin privileges, grayed out. Thoughts?

**Comment by rentzso** [comment]
Those are both good ideas.
For the record, I will add the 'Create Project' to the Actions Dropdown, only in the Projects view.

**Comment by rentzso** [comment]
closed with a3a2acbdbbc81cdf8359dc227acc9fc5d883629b
