### ISSUE TITLE
Old attachments not showing in UI

### ISSUE THREAD

**Issue by lmperry** [scitran/sdm#47]
Currently the SDM UI shows attachments from the ```files``` array, while old attached documents and files are in an ```attachments``` array. This has caused a disconnect between what's in the DB and what's shown in the UI. 

Newly attached data are being placed into the ```files``` array by the SDM UI. 

Another DB update is needed to create an entry in the ```files``` array for each of the existing attachments in the ```attachments``` array. 

@gsfr @rentzso and @lmperry will sync the fix for this on 7/13.

**Comment by gsfr** [comment]
@lmperry and I manually migrated the relevant instances.
