### ISSUE TITLE
Search: Add search for sex

### ISSUE THREAD

**Issue by lmperry** [scitran/sdm#49]
Update UI code to search ```sessions``` collection for ```subject.sex```. This should be a dropdown (male/female) and the query string should be ```sex```.

A corresponding update In ```scitran/api/core.py``` (see [lines 579-593](https://github.com/scitran/api/blob/master/core.py)) will be needed to add ```subject.sex``` to the ```session_query``` dict.

**Comment by rentzso** [comment]
closed with commit 8d2aaac98b0bef503a9bb0fd25c62780af779d60
