### ISSUE TITLE
Add users by (real) name 

### ISSUE THREAD

**Issue by lmperry** [scitran/sdm#50]
We should be able to add users to groups and assign permissions by providing a user's real name. 

<img width="887" alt="screen shot 2015-07-14 at 10 37 24 pm" src="https://cloud.githubusercontent.com/assets/2119651/8691542/21cbbf14-2a79-11e5-9b99-e5a705fbe1ff.png">

<img width="707" alt="screen shot 2015-07-14 at 10 39 45 pm" src="https://cloud.githubusercontent.com/assets/2119651/8691551/49e31772-2a79-11e5-95bb-b01eed7ef884.png">

<img width="867" alt="screen shot 2015-07-14 at 10 39 53 pm" src="https://cloud.githubusercontent.com/assets/2119651/8691552/4d9ccafc-2a79-11e5-95b3-448bf5ec7db5.png">

**Comment by lmperry** [comment]
Very nice!

**Comment by rentzso** [comment]
Thanks!
