### ISSUE TITLE
Add download icon for files and attachments

### ISSUE THREAD

**Issue by lmperry** [scitran/sdm#51]
Currently the name of each file is a hyperlink. This leads to unintended downloads. I have watched numerous users download the file by accident, when they actually want to just view the file. 

I think we should stop hyperlinking the file name and use a 'download' button that will initiate the download. 

<img width="859" alt="screen shot 2015-07-14 at 11 11 32 pm" src="https://cloud.githubusercontent.com/assets/2119651/8691918/b6a125a8-2a7d-11e5-8a3a-c86f4bff8218.png">

**Comment by gsfr** [comment]
+1
And while we're at it, we should hide the permalinks behind a button.
I could imagine a single column, maybe called "Actions", holding the three icons: View, Download, Permalink.
